package dev.hail.create_fantasizing.block.crate.fluid_barrel;

import com.simibubi.create.content.contraptions.Contraption;
import net.minecraft.MethodsReturnNonnullByDefault;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;

import javax.annotation.ParametersAreNonnullByDefault;

/**
 * THIS INTERFACE WAS GENERATED BY DEEPSEEK V4
 * Interface for {@link com.simibubi.create.api.contraption.storage.fluid.MountedFluidStorage} implementations
 * that support right-click GUI interaction on contraptions.
 * <p>
 * By default, Create only dispatches player interaction to {@code MountedItemStorage} via
 * {@link com.simibubi.create.api.contraption.storage.item.MountedItemStorage#handleInteraction}.
 * Fluid storages on contraptions cannot normally be opened via right-click.
 * This interface bridges that gap — implement it on a {@code MountedFluidStorage} subclass,
 * and the {@link dev.hail.create_fantasizing.mixin.MountedStorageManagerMixin} will detect it
 * and dispatch interaction accordingly.
 * </p>
 *
 * @see dev.hail.create_fantasizing.block.crate.fluid_barrel.FluidBarrelMountedStorage
 */
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
public interface IMountedFluidStorageInteraction {

    /**
     * Called when a player right-clicks a contraption block that has an
     * {@code IMountedFluidStorageInteraction} fluid storage at that position.
     *
     * @param player      the server-side player who interacted
     * @param contraption the contraption being interacted with
     * @param info        the block info at the clicked position
     * @return {@code true} if the interaction was handled, {@code false} otherwise
     */
    boolean handleInteraction(ServerPlayer player, Contraption contraption,
                              StructureTemplate.StructureBlockInfo info);
}
