package dev.hail.create_fantasizing.block.crate.fluid_barrel;

import com.simibubi.create.foundation.fluid.SmartFluidTank;
import dev.hail.create_fantasizing.block.CFABlocks;
import dev.hail.create_fantasizing.block.crate.*;
import net.minecraft.MethodsReturnNonnullByDefault;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.Tag;
import net.minecraft.world.MenuProvider;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;

import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import java.util.function.Predicate;

/**
 * THIS CLASS WAS GENERATED BY DEEPSEEK V4
 * A non-world BlockEntity proxy that holds contraption-mounted fluid barrel data
 * (fluid tank + bucket slots) and serves as the {@link MenuProvider} for the fluid barrel GUI.
 * <p>
 * Extends {@link AbstractFluidBarrelEntity} so it can be passed as {@code contentHolder}
 * to existing fluid barrel menu classes ({@link CopperFluidBarrelMenu}, {@link ZincFluidBarrelMenu},
 * {@link GoldFluidBarrelMenu}, {@link DiamondFluidBarrelMenu}), allowing full reuse of
 * the fluid barrel UI for contraption interactions.
 * </p>
 * <p>
 * Important: Bucket slot items are passed as raw {@link ItemStack}s and stored into
 * {@code this.bucketSlots} (which was created by the parent constructor with {@code this}
 * as owner). This avoids NPE from {@code SmartInventory.SyncedStackHandler.onContentsChanged()}
 * which unconditionally calls {@code blockEntity.notifyUpdate()}.
 * </p>
 * <p>
 * Similar to {@link dev.hail.create_fantasizing.block.crate.MountedCrateProxyEntity}
 * for item crates.
 * </p>
 */
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
public class MountedFluidBarrelProxyEntity extends AbstractFluidBarrelEntity implements MenuProvider {

    private final BlockState blockState;
    private final Block sourceBlock;
    private MountedFluidBarrelProxyEntity otherProxy;
    private final boolean isDouble;
    private final Predicate<Player> stillValidChecker;

    private Level contraptionLevel;

    /**
     * Constructs the proxy.
     * <p>
     * The {@link AbstractFluidBarrelEntity} parent constructor creates {@code this.bucketSlots}
     * as a {@code SmartInventory(2, this, ...)} with {@code this} proxy as the owner.
     * We then safely populate it from the raw {@code bucket0}/{@code bucket1} parameters.
     * </p>
     *
     * @param type              the block entity type
     * @param pos               always {@link BlockPos#ZERO} for proxies
     * @param state             the block state on the contraption
     * @param sourceBlock       the actual fluid barrel block type
     * @param tankInventory     the fluid tank (replaces auto-created one from parent)
     * @param bucket0           item for bucket slot 0
     * @param bucket1           item for bucket slot 1
     * @param isDouble          whether this is a double barrel
     * @param otherProxy        the other half of a double barrel (or null)
     * @param stillValidChecker menu validity predicate
     */
    private MountedFluidBarrelProxyEntity(BlockEntityType<?> type, BlockPos pos, BlockState state,
                                          Block sourceBlock, SmartFluidTank tankInventory,
                                          ItemStack bucket0, ItemStack bucket1,
                                          boolean isDouble, @Nullable MountedFluidBarrelProxyEntity otherProxy,
                                          Predicate<Player> stillValidChecker) {
        super(type, pos, state);
        this.blockState = state;
        this.sourceBlock = sourceBlock;
        this.isDouble = isDouble;
        this.otherProxy = otherProxy;
        this.stillValidChecker = stillValidChecker;

        // Replace auto-initialized tank with actual mounted data
        this.tankInventory = tankInventory;

        // Populate bucket slots — this.bucketSlots was created by super() with `this` as owner (safe!)
        // Its onContentsChanged() calls this.notifyUpdate() which is safe because `this` is a valid SyncedBlockEntity
        this.bucketSlots.setStackInSlot(0, bucket0);
        this.bucketSlots.setStackInSlot(1, bucket1);

        if (getEntityType(sourceBlock).equals(CFABlocks.ZINC_FLUID_BARREL_ENTITY.get())) {
            this.singleTankCapacity = 32000;
        } else if (getEntityType(sourceBlock).equals(CFABlocks.GOLD_FLUID_BARREL_ENTITY.get())) {
            this.singleTankCapacity = 48000;
        } else if (getEntityType(sourceBlock).equals(CFABlocks.DIAMOND_FLUID_BARREL_ENTITY.get())) {
            this.singleTankCapacity = 128000;
        } else {
            this.singleTankCapacity = 8000;
        }
    }

    // ========================================================================
    // Entity type lookup — maps fluid barrel blocks to their entity types
    // ========================================================================

    /**
     * Resolves the correct {@link BlockEntityType} for the given fluid barrel block.
     * Defaults to {@link CFABlocks#COPPER_FLUID_BARREL_ENTITY}.
     */
    private static BlockEntityType<?> getEntityType(Block sourceBlock) {
        if (sourceBlock == CFABlocks.ZINC_FLUID_BARREL.get())
            return CFABlocks.ZINC_FLUID_BARREL_ENTITY.get();
        else if (sourceBlock == CFABlocks.GOLD_FLUID_BARREL.get())
            return CFABlocks.GOLD_FLUID_BARREL_ENTITY.get();
        else if (sourceBlock == CFABlocks.DIAMOND_FLUID_BARREL.get())
            return CFABlocks.DIAMOND_FLUID_BARREL_ENTITY.get();
        else
            return CFABlocks.COPPER_FLUID_BARREL_ENTITY.get(); // default
    }

    @Override
    public boolean isMountedProxy() {
        return true;
    }

    @Override
    public BlockState getBlockState() {
        return blockState;
    }

    @Override
    public BlockPos getBlockPos() {
        return BlockPos.ZERO;
    }

    @Override
    public boolean isDoubleCrate() {
        return isDouble;
    }

    @Override
    public AbstractFluidBarrelEntity getOtherCrate() {
        return otherProxy;
    }

    public void setOtherProxy(MountedFluidBarrelProxyEntity other) {
        this.otherProxy = other;
    }

    // ========================================================================
    // MenuProvider — creates the appropriate fluid barrel menu
    // ========================================================================

    @Override
    public AbstractContainerMenu createMenu(int id, Inventory playerInv, Player player) {
        Block block = sourceBlock;
        if (block == CFABlocks.ZINC_FLUID_BARREL.get())
            return ZincFluidBarrelMenu.create(id, playerInv, this);
        else if (block == CFABlocks.GOLD_FLUID_BARREL.get())
            return GoldFluidBarrelMenu.create(id, playerInv, this);
        else if (block == CFABlocks.DIAMOND_FLUID_BARREL.get())
            return DiamondFluidBarrelMenu.create(id, playerInv, this);
        else
            return CopperFluidBarrelMenu.create(id, playerInv, this);
    }

    @Override
    public boolean canPlayerUse(Player player) {
        return stillValidChecker != null && stillValidChecker.test(player);
    }

    // ========================================================================
    // Tick, NBT — no-ops for proxy (not in a real world)
    // ========================================================================

    @Override
    public void tick() {
        // no-op: proxy is not in a world
    }

    @Override
    public void write(CompoundTag compound, HolderLookup.Provider registries, boolean clientPacket) {
        // No NBT persistence needed
    }

    @Override
    protected void read(CompoundTag compound, HolderLookup.Provider registries, boolean clientPacket) {
        // No NBT persistence needed
    }

    @Nullable
    public Level getLevel() {
        return this.contraptionLevel;
    }

    // ========================================================================
    // Network serialization — sends proxy data to the client
    // ========================================================================

    /**
     * Serializes fluid barrel state to the menu buffer.
     * <p>
     * BlockPos.ZERO serves as the sentinel that distinguishes a proxy from a real
     * block entity (normal entities never have ZERO pos). The block registry name
     * tells the client which fluid barrel type to reconstruct.
     * </p>
     * <p>
     * Fluid and bucket slot data are serialized as NBT compound tags for reliable
     * cross-network transfer.
     * </p>
     */
    @Override
    public void sendToMenu(net.minecraft.network.RegistryFriendlyByteBuf buf) {
        // Sentinel: BlockPos.ZERO marks this as a proxy
        buf.writeBlockPos(BlockPos.ZERO);
        // Block identifier for client-side reconstruction
        buf.writeResourceLocation(
                net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(sourceBlock));
        buf.writeBoolean(isDouble);

        // Facing and crate type BEFORE NBT payload — must match read order in createOnClient
        buf.writeEnum(blockState.getValue(AbstractDoubleStorageBlock.FACING));
        buf.writeEnum(blockState.getValue(AbstractDoubleStorageBlock.CRATE_TYPE));

        // ---- Fluid data as NBT ----
        net.minecraft.nbt.CompoundTag fluidTag = new net.minecraft.nbt.CompoundTag();
        fluidTag.putInt("Capacity", tankInventory.getCapacity());
        fluidTag.putInt("SingleCapacity", singleTankCapacity); // GUI visual: capacity bar scaling for double barrels
        if (!tankInventory.isEmpty())
            fluidTag.put("Fluid", tankInventory.getFluid().save(buf.registryAccess()));
        buf.writeNbt(fluidTag);

        // ---- Bucket slot data as NBT ----
        net.minecraft.nbt.CompoundTag bucketsTag = new net.minecraft.nbt.CompoundTag();
        net.minecraft.nbt.ListTag itemsList = new net.minecraft.nbt.ListTag();
        for (int i = 0; i < 2; i++) {
            ItemStack stack = bucketSlots.getStackInSlot(i);
            if (!stack.isEmpty()) {
                net.minecraft.nbt.CompoundTag itemTag = new net.minecraft.nbt.CompoundTag();
                itemTag.putInt("Slot", i);
                itemsList.add(stack.save(buf.registryAccess(), itemTag));
            }
        }
        bucketsTag.put("Items", itemsList);
        buf.writeNbt(bucketsTag);

        buf.writeUtf(customName != null ? customName : "");

        buf.writeNbt((Tag) this.contraptionLevel);
    }

    public Block getSourceBlock() {
        return sourceBlock;
    }

    // ========================================================================
    // Factory methods
    // ========================================================================

    /**
     * Creates a server-side proxy for opening the menu.
     *
     * @param sourceBlock       the fluid barrel block type
     * @param state             the block state on the contraption
     * @param tankInv           the fluid tank inventory
     * @param bucket0           item for bucket slot 0
     * @param bucket1           item for bucket slot 1
     * @param isDouble          whether this is a double barrel
     * @param otherProxy        the other half of a double barrel (or null)
     * @param stillValidChecker menu validity predicate
     */
    public static MountedFluidBarrelProxyEntity create(Block sourceBlock, BlockState state,
                                                       SmartFluidTank tankInv,
                                                       ItemStack bucket0, ItemStack bucket1,
                                                       boolean isDouble,
                                                       @Nullable MountedFluidBarrelProxyEntity otherProxy,
                                                       Predicate<Player> stillValidChecker) {
        return new MountedFluidBarrelProxyEntity(
                getEntityType(sourceBlock), BlockPos.ZERO, state, sourceBlock,
                tankInv, bucket0, bucket1, isDouble, otherProxy, stillValidChecker);
    }

    /**
     * Creates a client-side proxy from explicitly provided data.
     * Called by {@link AbstractDoubleStorageMenu#createOnClient}.
     *
     * @param sourceBlock the fluid barrel block type (resolved from registry name)
     * @param isDouble    whether this is a double barrel
     * @param capacity    fluid tank capacity
     * @param fluid       the fluid stack
     * @param bucket0     item for bucket slot 0
     * @param bucket1     item for bucket slot 1
     * @param customName  custom name (or empty string)
     * @param otherProxy  the other half of a double barrel (or null)
     * @param facing      the barrel's facing direction
     * @param crateType   MAIN, SECOND, or SINGLE
     */
    public static MountedFluidBarrelProxyEntity createClient(Block sourceBlock,
                                                             boolean isDouble,
                                                             int capacity,
                                                             int singleCapacity,
                                                             net.neoforged.neoforge.fluids.FluidStack fluid,
                                                             ItemStack bucket0, ItemStack bucket1,
                                                             String customName,
                                                             @Nullable MountedFluidBarrelProxyEntity otherProxy,
                                                             Direction facing,
                                                             AbstractDoubleStorageBlock.CrateType crateType) {
        BlockState state = sourceBlock.defaultBlockState()
                .setValue(AbstractDoubleStorageBlock.FACING, facing)
                .setValue(AbstractDoubleStorageBlock.CRATE_TYPE, crateType);
        SmartFluidTank tankInv = new SmartFluidTank(capacity, fs -> {});
        tankInv.setFluid(fluid);
        tankInv.setCapacity(capacity);

        MountedFluidBarrelProxyEntity proxy = new MountedFluidBarrelProxyEntity(
                getEntityType(sourceBlock), BlockPos.ZERO, state, sourceBlock,
                tankInv, bucket0, bucket1, isDouble, otherProxy, p -> true);
        // Override singleTankCapacity from constructor with the value from server
        proxy.singleTankCapacity = singleCapacity;
        if (!customName.isEmpty())
            proxy.customName = customName;
        return proxy;
    }

    // ========================================================================
    // Client data reading — parses fluid + bucket NBT from network buffer
    // ========================================================================

    /**
     * Reads fluid NBT, bucket NBT, and custom name from the buffer.
     * Helper for {@link AbstractDoubleStorageMenu#createOnClient} to keep reading logic together.
     *
     * @param buf the buffer positioned at the start of fluid barrel data
     * @return a record containing the parsed data
     */
    public static FluidBarrelClientData readClientData(net.minecraft.network.RegistryFriendlyByteBuf buf) {
        // ---- Read fluid data from NBT ----
        net.minecraft.nbt.CompoundTag fluidTag = buf.readNbt();
        int capacity = fluidTag != null ? fluidTag.getInt("Capacity") : 8000;
        int singleCapacity = fluidTag != null ? fluidTag.getInt("SingleCapacity") : 8000;
        net.neoforged.neoforge.fluids.FluidStack fluid = net.neoforged.neoforge.fluids.FluidStack.EMPTY;
        if (fluidTag != null && fluidTag.contains("Fluid"))
            fluid = net.neoforged.neoforge.fluids.FluidStack.parseOptional(buf.registryAccess(), fluidTag.getCompound("Fluid"));

        // ---- Read bucket slot data from NBT ----
        ItemStack bucket0 = ItemStack.EMPTY;
        ItemStack bucket1 = ItemStack.EMPTY;
        net.minecraft.nbt.CompoundTag bucketsTag = buf.readNbt();
        if (bucketsTag != null && bucketsTag.contains("Items")) {
            net.minecraft.nbt.ListTag itemsList = bucketsTag.getList("Items", net.minecraft.nbt.Tag.TAG_COMPOUND);
            for (int i = 0; i < itemsList.size(); i++) {
                net.minecraft.nbt.CompoundTag itemTag = itemsList.getCompound(i);
                int slot = itemTag.getInt("Slot");
                ItemStack stack = ItemStack.parseOptional(buf.registryAccess(), itemTag);
                if (slot == 0) bucket0 = stack;
                else if (slot == 1) bucket1 = stack;
            }
        }

        String customName = buf.readUtf();

        return new FluidBarrelClientData(capacity, singleCapacity, fluid, bucket0, bucket1, customName);
    }

    /**
     * Simple record holding deserialized fluid barrel client data.
     * Uses raw ItemStack fields (not SmartInventory) to avoid NPE from null-owner SmartInventory.
     */
    public record FluidBarrelClientData(int capacity, int singleCapacity,
                                         net.neoforged.neoforge.fluids.FluidStack fluid,
                                         ItemStack bucketSlot0, ItemStack bucketSlot1,
                                         String customName) {}
}
