modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.create_fantasizing]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_fantasizing]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_fantasizing]]
    modId="create"
    type="required"
    versionRange="[6.0,)"
    ordering="NONE"
    side="BOTH"