package dev.hail.create_fantasizing.mixin;

import com.simibubi.create.api.contraption.storage.fluid.MountedFluidStorage;
import com.simibubi.create.content.contraptions.Contraption;
import com.simibubi.create.content.contraptions.MountedStorageManager;
import dev.hail.create_fantasizing.block.crate.AbstractDoubleStorageBlock;
import dev.hail.create_fantasizing.block.crate.fluid_barrel.AbstractFluidBarrelBlock;
import dev.hail.create_fantasizing.block.crate.fluid_barrel.IMountedFluidStorageInteraction;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * THIS MIXIN WAS GENERATED BY DEEPSEEK V4
 * Mixin into Create's {@link MountedStorageManager#handlePlayerStorageInteraction}
 * to extend player right-click interaction to fluid storages.
 * <p>
 * By default, Create only dispatches interaction to {@code MountedItemStorage} instances.
 * This mixin adds a secondary check: if no item storage handled the interaction (returns false),
 * it checks whether the fluid storage at the clicked position implements
 * {@link IMountedFluidStorageInteraction} and dispatches the interaction there.
 * </p>
 * <p>
 * Also handles double fluid barrels: if the clicked block is a SECOND half (which has no
 * mounted storage of its own), the interaction is redirected to the adjacent MAIN half.
 * </p>
 *
 * @see IMountedFluidStorageInteraction
 * @see dev.hail.create_fantasizing.block.crate.fluid_barrel.FluidBarrelMountedStorage
 */
@Mixin(MountedStorageManager.class)
public class MountedStorageManagerMixin {

    /**
     * Injected at the return point of {@code handlePlayerStorageInteraction}.
     * If the method is about to return {@code false} (no item storage handled it),
     * checks fluid storages for {@link IMountedFluidStorageInteraction}.
     * Also redirects SECOND half clicks to the MAIN half for double fluid barrels.
     */
    @Inject(method = "handlePlayerStorageInteraction", at = @At("RETURN"), cancellable = true)
    private void checkFluidStorageInteraction(Contraption contraption, Player player, BlockPos localPos,
                                               CallbackInfoReturnable<Boolean> cir) {
        // Already handled — nothing to do
        if (cir.getReturnValueZ())
            return;

        // Only server-side players can open menus
        if (!(player instanceof ServerPlayer serverPlayer))
            return;

        // Get block info at the clicked position
        StructureTemplate.StructureBlockInfo info = contraption.getBlocks().get(localPos);
        if (info == null)
            return;

        // ---- Check fluid storages at the clicked position ----
        MountedFluidStorage fluidStorage = contraption.getStorage()
                .getFluids().storages.get(localPos);
        if (fluidStorage instanceof IMountedFluidStorageInteraction interaction) {
            cir.setReturnValue(interaction.handleInteraction(serverPlayer, contraption, info));
            return;
        }

        // ---- Double barrel: redirect SECOND half click to MAIN half ----
        BlockState state = info.state();
        if (state.getBlock() instanceof AbstractFluidBarrelBlock
                && state.hasProperty(AbstractDoubleStorageBlock.CRATE_TYPE)
                && state.getValue(AbstractDoubleStorageBlock.CRATE_TYPE) == AbstractDoubleStorageBlock.CrateType.SECOND
                && state.hasProperty(AbstractDoubleStorageBlock.FACING)) {
            Direction facing = state.getValue(AbstractDoubleStorageBlock.FACING);
            BlockPos mainPos = localPos.relative(facing);

            StructureTemplate.StructureBlockInfo mainInfo = contraption.getBlocks().get(mainPos);
            if (mainInfo == null)
                return;

            MountedFluidStorage mainStorage = contraption.getStorage()
                    .getFluids().storages.get(mainPos);
            if (mainStorage instanceof IMountedFluidStorageInteraction mainInteraction) {
                cir.setReturnValue(mainInteraction.handleInteraction(serverPlayer, contraption, mainInfo));
            }
        }
    }
}
