package dev.hail.create_fantasizing.block.crate;

import com.simibubi.create.foundation.gui.menu.MenuBase;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.core.BlockPos;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.world.Container;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.inventory.Slot;
import net.minecraft.world.level.block.entity.BlockEntity;

public abstract class AbstractDoubleStorageMenu<T> extends MenuBase<T> {
    public boolean dualBlock;
    protected boolean networkIsFold; // GENERATED BY DEEPSEEK V4
    protected int networkPage; // GENERATED BY DEEPSEEK V4
    protected boolean hasNetworkFoldData; // GENERATED BY DEEPSEEK V4

    public AbstractDoubleStorageMenu(MenuType<?> type, int id, Inventory inv, RegistryFriendlyByteBuf extraData) {
        super(type, id, inv, extraData);
    }

    public AbstractDoubleStorageMenu(MenuType<?> type, int id, Inventory inv, T be) {
        super(type, id, inv, be);
    }

    /**
     * THIS METHOD WAS REWRITTEN BY DEEPSEEK V4
     */
    @Override
    protected T createOnClient(RegistryFriendlyByteBuf extraData) {
        BlockPos readBlockPos = extraData.readBlockPos();
        // BlockPos.ZERO is the sentinel for MountedCrateProxyEntity
        if (BlockPos.ZERO.equals(readBlockPos)) {
            net.minecraft.resources.ResourceLocation blockId = extraData.readResourceLocation();
            net.minecraft.world.level.block.Block sourceBlock =
                    net.minecraft.core.registries.BuiltInRegistries.BLOCK.getOptional(blockId)
                            .orElse(net.minecraft.world.level.block.Blocks.AIR);
            boolean isDbl = extraData.readBoolean();
            int slotCount = extraData.readVarInt();
            int allowedAmt = extraData.readVarInt();
            int slotCount2 = 0, allowedAmt2 = 0;
            if (isDbl) {
                slotCount2 = extraData.readVarInt();
                allowedAmt2 = extraData.readVarInt();
            }
            String name = extraData.readUtf();
            net.minecraft.core.Direction facing = extraData.readEnum(net.minecraft.core.Direction.class);
            AbstractDoubleStorageBlock.CrateType crateType =
                    extraData.readEnum(AbstractDoubleStorageBlock.CrateType.class);

            MountedCrateProxyEntity otherProxy = null;
            if (isDbl && slotCount2 > 0) {
                otherProxy = MountedCrateProxyEntity.createClient(
                        sourceBlock, slotCount2, allowedAmt2, name, isDbl, null, facing, crateType);
            }
            MountedCrateProxyEntity proxy = MountedCrateProxyEntity.createClient(
                    sourceBlock, slotCount, allowedAmt, name, isDbl, otherProxy, facing, crateType);
            if (otherProxy != null)
                otherProxy.setOtherProxy(proxy);
            return (T) proxy;
        }
        // Normal path: look up real block entity in client world
        ClientLevel world = Minecraft.getInstance().level;
        if (world != null) {
            BlockEntity blockEntity = world.getBlockEntity(readBlockPos);
            if (blockEntity instanceof AbstractDoubleStorageEntity doubleStorageEntity) {
                var nbt = extraData.readNbt();
                if (nbt != null)
                    doubleStorageEntity.readClient(nbt, world.registryAccess());
                if (extraData.readInt() == ConfigureCrateFoldPacket.FOLD_MAGIC) {
                    hasNetworkFoldData = true;
                    networkIsFold = extraData.readBoolean();
                    networkPage = extraData.readVarInt();
                }
                return (T) doubleStorageEntity;
            }
        }
        return null;
    }

    @Override
    protected void initAndReadInventory(T contentHolder) {}

    @Override
    protected void saveData(T contentHolder) {}

    /**
     * THIS METHOD WAS REWRITTEN BY DEEPSEEK V4
     */
    @Override
    public boolean stillValid(Player player) {
        return switch (contentHolder) {
            case AbstractDoubleStorageEntity doubleStorage -> doubleStorage.canPlayerUse(player);
            case Container container -> container.stillValid(player);
            case null, default -> false;
        };
    }

    protected void addPlayerSlots(int xOffset, int yOffset){
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 9; ++col) {
                this.addSlot(new Slot(playerInventory, col + row * 9 + 9, xOffset + col * 18, yOffset + row * 18));
            }
        }

        for (int hotbarSlot = 0; hotbarSlot < 9; ++hotbarSlot) {
            this.addSlot(new Slot(playerInventory, hotbarSlot, xOffset + hotbarSlot * 18, yOffset + 58));
        }

        broadcastChanges();
    }
}
