package dev.hail.create_fantasizing.block.crate;

import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.inventory.Slot;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.NotNull;

public abstract class AbstractCrateMenu extends AbstractDoubleStorageMenu<AbstractCrateEntity>{
    // For Brass Crate & Sturdy Crate
    public boolean isFold;
    public int page;

    public AbstractCrateMenu(MenuType<?> type, int id, Inventory inv, RegistryFriendlyByteBuf extraData) {
        super(type, id, inv, extraData);
    }
    public AbstractCrateMenu(MenuType<?> type, int id, Inventory inv, AbstractCrateEntity be) {
        super(type, id, inv, be);
    }

    @Override
    public @NotNull ItemStack quickMoveStack(@NotNull Player playerIn, int index) {
        Slot clickedSlot = getSlot(index);
        if (!clickedSlot.hasItem())
            return ItemStack.EMPTY;

        ItemStack stack = clickedSlot.getItem();
        int crateSize = contentHolder.inventory.getSlots() * (dualBlock? 2 : 1);
        if (index < crateSize) {
            moveItemStackTo(stack, crateSize, slots.size(), false);
/*========================================================================================================================================*/
/*  THIS PART OF THE CODE WAS GENERATED BY DEEPSEEK V4                                                                                    */
/*----------------------------------------------------------------------------------------------------------------------------------------*/
/**/        if (dualBlock && isFold && page == 1 && contentHolder.getOtherCrate() != null)                                              /**/
/**/            contentHolder.getOtherCrate().inventory.onContentsChanged(index);                                                       /**/
/**/        else                                                                                                                        /**/
/**/            contentHolder.inventory.onContentsChanged(index);                                                                       /**/
/*========================================================================================================================================*/
        } else
            moveItemStackTo(stack, 0, crateSize, false);
        contentHolder.inventory.onContentsChanged(index);

        return ItemStack.EMPTY;
    }

    public boolean isFullInterface(){
        return dualBlock && !isFold;
    }
}
