package dev.hail.create_fantasizing.block.crate;

import dev.hail.create_fantasizing.block.CFABlocks;
import dev.hail.create_fantasizing.data.CFAAttachmentTypes;
import net.minecraft.core.BlockPos;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.ItemInteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import org.jetbrains.annotations.NotNull;

import javax.annotation.ParametersAreNonnullByDefault;

@ParametersAreNonnullByDefault
public class BrassCrateBlock extends AbstractCrateBlock{
    public BrassCrateBlock(Properties properties) {super(properties);}

    /**
     * THIS METHOD WAS GENERATED BY DEEPSEEK V4
     */
    @Override
    public @NotNull ItemInteractionResult useItemOn(ItemStack stack, BlockState state, Level worldIn, BlockPos pos, Player player, InteractionHand handIn,
                                                    BlockHitResult hit) {
        super.useItemOn(stack,state,worldIn,pos,player,handIn,hit);
        withBlockEntityDo(worldIn, pos, crate -> {
            var main = crate.getMainCrate();
            player.openMenu(main, buf -> {
                buf.writeBlockPos(main.getBlockPos());
                buf.writeNbt(main.getUpdateTag(buf.registryAccess()));
                buf.writeInt(ConfigureCrateFoldPacket.FOLD_MAGIC);
                buf.writeBoolean(player.getData(CFAAttachmentTypes.FOLD_INTERFACE));
                buf.writeVarInt(player.getData(CFAAttachmentTypes.CRATE_PAGE));
            });
        });
        return ItemInteractionResult.SUCCESS;
    }

    @Override
    public BlockEntityType<? extends BrassCrateEntity> getBlockEntityType() {
        return CFABlocks.BRASS_CRATE_ENTITY.get();
    }
}
