package dev.hail.create_fantasizing.block.crate;

import com.simibubi.create.foundation.networking.BlockEntityConfigurationPacket;
import dev.hail.create_fantasizing.data.CFAAttachmentTypes;
import dev.hail.create_fantasizing.event.CFAPackets;
import io.netty.buffer.ByteBuf;
import net.minecraft.core.BlockPos;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.server.level.ServerPlayer;
/**
 * THIS CLASS WAS GENERATED BY DEEPSEEK V4
 */
public class ConfigureCrateFoldPacket extends BlockEntityConfigurationPacket<AbstractCrateEntity> {
    public static final StreamCodec<ByteBuf, ConfigureCrateFoldPacket> STREAM_CODEC = StreamCodec.composite(
            BlockPos.STREAM_CODEC, p -> p.pos,
            ByteBufCodecs.BOOL, p -> p.isFold,
            ByteBufCodecs.VAR_INT, p -> p.page,
            ConfigureCrateFoldPacket::new
    );

    public static final int FOLD_MAGIC = 0xCFAF01D;

    private final boolean isFold;
    private final int page;

    public ConfigureCrateFoldPacket(BlockPos pos, boolean isFold, int page) {
        super(pos);
        this.isFold = isFold;
        this.page = page;
    }

    @Override
    protected void applySettings(ServerPlayer player, AbstractCrateEntity be) {
        player.closeContainer();
        if (isFold) {
            player.setData(CFAAttachmentTypes.FOLD_INTERFACE, true);
            player.setData(CFAAttachmentTypes.CRATE_PAGE, page);
        }
        var main = be.getMainCrate();
        player.openMenu(main, buf -> {
            buf.writeBlockPos(main.getBlockPos());
            buf.writeNbt(main.getUpdateTag(buf.registryAccess()));
            buf.writeInt(FOLD_MAGIC);
            buf.writeBoolean(isFold);
            buf.writeVarInt(page);
        });
    }

    @Override
    public PacketTypeProvider getTypeProvider() {
        return CFAPackets.CONFIGURE_CRATE_FOLD;
    }
}
