package dev.hail.create_fantasizing.block.crate;

import net.minecraft.MethodsReturnNonnullByDefault;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.MenuProvider;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;

import dev.hail.create_fantasizing.block.CFABlocks;

import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import java.util.function.Predicate;

/**
 * THIS CLASS WAS GENERATED BY DEEPSEEK V4
 * A non-world BlockEntity proxy that holds contraption-mounted crate data.
 * Passed as the contentHolder to existing crate menu classes, allowing full
 * reuse of Andesite/Iron/Brass/Sturdy crate UI for contraption interactions.
 */
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
public class MountedCrateProxyEntity extends AbstractCrateEntity implements MenuProvider {
    private final BlockState blockState;
    private final Block sourceBlock;
    private MountedCrateProxyEntity otherProxy;
    private final boolean isDouble;
    private final Predicate<Player> stillValidChecker;

    private MountedCrateProxyEntity(BlockEntityType<?> type, BlockPos pos, BlockState state,
                                     CrateInventory inventory, Block sourceBlock,
                                     boolean isDouble, @Nullable MountedCrateProxyEntity otherProxy,
                                     Predicate<Player> stillValidChecker) {
        super(type, pos, state);
        this.blockState = state;
        this.sourceBlock = sourceBlock;
        this.inventory = inventory;
        this.isDouble = isDouble;
        this.otherProxy = otherProxy;
        this.stillValidChecker = stillValidChecker;
    }

    private static BlockEntityType<?> getEntityType(Block sourceBlock) {
        if (sourceBlock == CFABlocks.IRON_CRATE.get())
            return CFABlocks.IRON_CRATE_ENTITY.get();
        else if (sourceBlock == CFABlocks.BRASS_CRATE.get())
            return CFABlocks.BRASS_CRATE_ENTITY.get();
        else if (sourceBlock == CFABlocks.STURDY_CRATE.get())
            return CFABlocks.STURDY_CRATE_ENTITY.get();
        else
            return CFABlocks.ANDESITE_CRATE_ENTITY.get(); // default
    }

    @Override
    public boolean isMountedProxy() {
        return true;
    }

    @Override
    public BlockState getBlockState() {
        return blockState;
    }

    @Override
    public BlockPos getBlockPos() {
        return BlockPos.ZERO;
    }

    @Override
    public boolean isDoubleCrate() {
        return isDouble;
    }

    @Override
    public AbstractCrateEntity getOtherCrate() {
        return otherProxy;
    }

    public void setOtherProxy(MountedCrateProxyEntity other) {
        this.otherProxy = other;
    }

    @Override
    public int getOverallAllowedAmount() {
        int total = inventory.allowedAmount;
        if (otherProxy != null)
            total += otherProxy.inventory.allowedAmount;
        return total;
    }

    @Override
    public AbstractContainerMenu createMenu(int id, Inventory playerInv, Player player) {
        Block block = sourceBlock;
        if (block == CFABlocks.IRON_CRATE.get())
            return IronCrateMenu.create(id, playerInv, this);
        else if (block == CFABlocks.BRASS_CRATE.get())
            return BrassCrateMenu.create(id, playerInv, this);
        else if (block == CFABlocks.STURDY_CRATE.get())
            return SturdyCrateMenu.create(id, playerInv, this);
        else
            return AndesiteCrateMenu.create(id, playerInv, this);
    }

    @Override
    public boolean canPlayerUse(Player player) {
        return stillValidChecker != null && stillValidChecker.test(player);
    }

    @Override
    public void tick() {
        // no-op: proxy is not in a world
    }

    @Override
    public void write(CompoundTag compound, HolderLookup.Provider registries, boolean clientPacket) {
        // No NBT persistence needed
    }

    @Override
    protected void read(CompoundTag compound, HolderLookup.Provider registries, boolean clientPacket) {
        // No NBT persistence needed
    }

    @Override
    public void sendToMenu(net.minecraft.network.RegistryFriendlyByteBuf buf) {
        // Sentinel: BlockPos.ZERO markers this as a proxy (normal entities never have ZERO pos)
        buf.writeBlockPos(BlockPos.ZERO);
        buf.writeResourceLocation(
                net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(sourceBlock));
        buf.writeBoolean(isDouble);
        buf.writeVarInt(inventory.getSlots());
        buf.writeVarInt(inventory.allowedAmount);
        if (isDouble && otherProxy != null) {
            buf.writeVarInt(otherProxy.inventory.getSlots());
            buf.writeVarInt(otherProxy.inventory.allowedAmount);
        }
        buf.writeUtf(customName != null ? customName : "");
        buf.writeEnum(blockState.getValue(AbstractDoubleStorageBlock.FACING));
        buf.writeEnum(blockState.getValue(AbstractDoubleStorageBlock.CRATE_TYPE));
    }

    public Block getSourceBlock() {
        return sourceBlock;
    }

    public static MountedCrateProxyEntity create(Block sourceBlock, BlockState state,
                                                  CrateInventory crateInv,
                                                  boolean isDouble,
                                                  @Nullable MountedCrateProxyEntity otherProxy,
                                                  Predicate<Player> stillValidChecker) {
        return new MountedCrateProxyEntity(
                getEntityType(sourceBlock), BlockPos.ZERO, state, crateInv, sourceBlock,
                isDouble, otherProxy, stillValidChecker);
    }

    /**
     * Creates a client-side proxy from buffer data.
     */
    public static MountedCrateProxyEntity createClient(Block sourceBlock, int slotCount,
                                                        int allowedAmount, String customName,
                                                        boolean isDouble,
                                                        @Nullable MountedCrateProxyEntity otherProxy,
                                                        Direction facing,
                                                        AbstractDoubleStorageBlock.CrateType crateType) {
        BlockState state = sourceBlock.defaultBlockState()
                .setValue(AbstractDoubleStorageBlock.FACING, facing)
                .setValue(AbstractDoubleStorageBlock.CRATE_TYPE, crateType);
        CrateInventory inv = new CrateInventory(null, slotCount);
        inv.allowedAmount = allowedAmount;
        MountedCrateProxyEntity proxy = new MountedCrateProxyEntity(
                getEntityType(sourceBlock), BlockPos.ZERO, state, inv, sourceBlock,
                isDouble, otherProxy, p -> true);
        if (!customName.isEmpty())
            proxy.customName = customName;
        return proxy;
    }
}
