package dev.hail.create_fantasizing.block.crate;

import dev.hail.create_fantasizing.block.CFABlocks;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.Container;
import net.minecraft.world.SimpleContainer;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.inventory.Slot;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import dev.hail.create_fantasizing.block.CFAMenus;
import net.neoforged.neoforge.items.IItemHandlerModifiable;
import net.neoforged.neoforge.items.ItemStackHandler;
import net.neoforged.neoforge.items.SlotItemHandler;
import org.jetbrains.annotations.NotNull;
/**
 * THIS CLASS WAS GENERATED BY DEEPSEEK V4
 */
public class MountedCrateMenu extends AbstractContainerMenu {
    private final Container container;
    private final Block sourceBlock;
    private final int crateSlots;
    private final int cols;
    private final boolean dual;

    // Server constructor
    public MountedCrateMenu(int id, Inventory inv, Container container, IItemHandlerModifiable crateHandler, Block sourceBlock) {
        super(CFAMenus.MOUNTED_CRATE.get(), id);
        this.container = container;
        this.sourceBlock = sourceBlock;
        this.crateSlots = crateHandler.getSlots();
        if (sourceBlock.equals(CFABlocks.IRON_CRATE.get())) {
            this.dual = crateSlots >= 40;
            this.cols = dual ? 10 : 5;
        } else {
            this.dual = crateSlots >= 32;
            this.cols = dual ? 8 : 4;
        }

        container.startOpen(inv.player);
        addSlots(inv, crateHandler);
    }

    // Client constructor (ForgeMenuFactory signature)
    public MountedCrateMenu(MenuType<MountedCrateMenu> type, int id, Inventory inv, RegistryFriendlyByteBuf extraData) {
        super(CFAMenus.MOUNTED_CRATE.get(), id);

        Block block = Blocks.AIR;
        int slotCount = 16;
        int allowedAmt = 1024;
        if (extraData.readableBytes() > 0) {
            ResourceLocation blockId = extraData.readResourceLocation();
            block = BuiltInRegistries.BLOCK.getOptional(blockId).orElse(Blocks.AIR);
            slotCount = extraData.readVarInt();
            allowedAmt = extraData.readVarInt();
        }
        this.sourceBlock = block;
        this.crateSlots = slotCount;
        if (sourceBlock.equals(CFABlocks.IRON_CRATE.get())) {
            this.dual = crateSlots >= 40;
            this.cols = dual ? 10 : 5;
        } else {
            this.dual = crateSlots >= 32;
            this.cols = dual ? 8 : 4;
        }
        this.container = new SimpleContainer(crateSlots);

        // Capture effectively-final copy for anonymous class
        final int finalAllowedAmount = allowedAmt;

        // Client-side handler that respects allowedAmount for visual slot limits
        IItemHandlerModifiable clientHandler = new ItemStackHandler(crateSlots) {
            @Override
            public int getSlotLimit(int slot) {
                if (slot < finalAllowedAmount / 64)
                    return 64;
                else if (slot == finalAllowedAmount / 64)
                    return finalAllowedAmount % 64;
                return 0;
            }

            @Override
            public boolean isItemValid(int slot, @NotNull ItemStack stack) {
                return slot <= finalAllowedAmount / 64;
            }
        };
        addSlots(inv, clientHandler);
    }

    private void addSlots(Inventory inv, IItemHandlerModifiable crateHandler) {
        int xOffset;
        switch (cols){
            case 5 -> xOffset = 44; // Single Iron
            case 8 -> xOffset = 31; // Double Andesite
            case 10 -> xOffset = 18; // Double Iron
            default -> xOffset = 53; // Single Andesite: 4
        }
        int yOffset = 27;

        // Crate slots - 4 rows, using SlotItemHandler for per-slot limits
        for (int row = 0; row < 4; row++) {
            for (int col = 0; col < cols; col++) {
                int slotIndex = col + row * cols;
                this.addSlot(new SlotItemHandler(crateHandler, slotIndex, xOffset + col * 18, yOffset + row * 18));
            }
        }

        // Player inventory
        int playerXOffset;
        switch (cols){
            case 8 -> playerXOffset = 32; // Double Andesite
            case 10 -> playerXOffset = 27; // Double Iron
            default -> playerXOffset = 8; // Single Andesite: 4 & Single Iron: 5
        }
        int playerYOffset = 157;
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 9; ++col) {
                this.addSlot(new Slot(inv, col + row * 9 + 9, playerXOffset + col * 18, playerYOffset + row * 18));
            }
        }
        // Hotbar
        for (int hotbar = 0; hotbar < 9; ++hotbar) {
            this.addSlot(new Slot(inv, hotbar, playerXOffset + hotbar * 18, playerYOffset + 58));
        }
    }

    @Override
    public @NotNull ItemStack quickMoveStack(@NotNull Player player, int index) {
        Slot clickedSlot = getSlot(index);
        if (!clickedSlot.hasItem())
            return ItemStack.EMPTY;

        ItemStack stack = clickedSlot.getItem();
        if (index < crateSlots) {
            // From crate to player inventory
            if (!moveItemStackTo(stack, crateSlots, this.slots.size(), true))
                return ItemStack.EMPTY;
        } else {
            // From player inventory to crate
            if (!moveItemStackTo(stack, 0, crateSlots, false))
                return ItemStack.EMPTY;
        }

        if (stack.isEmpty()) {
            clickedSlot.setByPlayer(ItemStack.EMPTY);
        } else {
            clickedSlot.setChanged();
        }

        return stack.isEmpty() ? ItemStack.EMPTY : stack.copy();
    }

    @Override
    public boolean stillValid(@NotNull Player player) {
        return container.stillValid(player);
    }

    @Override
    public void removed(@NotNull Player player) {
        super.removed(player);
        container.stopOpen(player);
    }

    public int getCrateSlots() {
        return crateSlots;
    }

    public boolean getDual(){
        return dual;
    }

    public int getCols() {
        return cols;
    }

    public Block getSourceBlock() {
        return sourceBlock;
    }
}
