package dev.hail.create_fantasizing.block.crate;

import com.simibubi.create.foundation.gui.AllGuiTextures;
import com.simibubi.create.foundation.gui.menu.AbstractSimiContainerScreen;

import dev.hail.create_fantasizing.CFAGuiTextures;
import dev.hail.create_fantasizing.block.CFABlocks;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.level.block.Block;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.jetbrains.annotations.NotNull;
/**
 * THIS CLASS WAS GENERATED BY DEEPSEEK V4
 */
@OnlyIn(Dist.CLIENT)
public class MountedCrateScreen extends AbstractSimiContainerScreen<MountedCrateMenu> {

    private final CFAGuiTextures background;
    private final boolean dual;
    private final int cols;
    private int textureXShift;

    public MountedCrateScreen(MountedCrateMenu menu, Inventory inv, Component title) {
        super(menu, inv, title);
        this.dual = menu.getDual();
        this.cols = menu.getCols();
        this.background = selectBackground(menu.getSourceBlock(), dual);
    }

    private static CFAGuiTextures selectBackground(Block block, boolean isDouble) {
        if (block == CFABlocks.IRON_CRATE.get()) {
            return isDouble ? CFAGuiTextures.IRON_DOUBLE_CRATE : CFAGuiTextures.IRON_CRATE;
        } else if (block == CFABlocks.BRASS_CRATE.get()) {
            return CFAGuiTextures.BRASS_CRATE_DOWNSIDE;
        } else if (block == CFABlocks.STURDY_CRATE.get()) {
            return CFAGuiTextures.STURDY_CRATE_DOWNSIDE;
        } else {
            // Default: Andesite
            return isDouble ? CFAGuiTextures.ANDESITE_DOUBLE_CRATE : CFAGuiTextures.ANDESITE_CRATE;
        }
    }

    @Override
    protected void init() {
        setWindowSize(Math.max(background.getWidth(), AllGuiTextures.PLAYER_INVENTORY.getWidth()),
                background.getHeight() + 4 + AllGuiTextures.PLAYER_INVENTORY.getHeight());
        setWindowOffset(cols == 8 ? -4 : 0, -7);
        super.init();

        textureXShift = cols == 8 ? 8 : (imageWidth - (background.getWidth() - 8)) / 2;
    }

    @Override
    protected void renderBg(@NotNull GuiGraphics ms, float partialTicks, int mouseX, int mouseY) {
        int invX = getLeftOfCentered(AllGuiTextures.PLAYER_INVENTORY.getWidth()) + (cols == 8 ? 10 : 0);
        int invY = topPos + background.getHeight() + 12;
        renderPlayerInventory(ms, invX, invY);

        int x = leftPos + textureXShift;
        int y = topPos + 7;

        background.render(ms, x, y);
    }

    @Override
    protected void renderLabels(@NotNull GuiGraphics ms, int mouseX, int mouseY) {
        // Title is rendered by AbstractContainerScreen from getTitle()
        ms.drawString(font, title, textureXShift + (background.getWidth() - font.width(title)) / 2, titleLabelY + 3, 0x404040, false);
    }
}
