package dev.hail.create_fantasizing.block.crate;

import dev.hail.create_fantasizing.CFAGuiTextures;
import dev.hail.create_fantasizing.block.CFABlocks;
import net.createmod.catnip.gui.element.GuiGameElement;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.player.Inventory;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.jetbrains.annotations.NotNull;

import java.util.List;

@OnlyIn(Dist.CLIENT)
public class SturdyCrateScreen extends AbstractCrateScreen<SturdyCrateMenu> {

    public SturdyCrateScreen(SturdyCrateMenu container, Inventory inv, Component title) {
        super(container, inv, title);
        blockEntry = CFABlocks.STURDY_CRATE;
        renderedItem = blockEntry.asStack();
        background = CFAGuiTextures.STURDY_CRATE_UPSIDE;
        backgroundSec = CFAGuiTextures.STURDY_CRATE_DOWNSIDE;

        capacityLabelOffset = menu.isFullInterface() ? 90 : 0;
        textureYShift = menu.isFullInterface() ? -45 : 0;
        itemYShift = menu.isFullInterface() ? 81 : 0;

        initWindowSizeHeight = (menu.isFullInterface() ? 235 : 145) - 18;
        initWindowXOffset = 0;
        initYShiftOffset = (menu.isFullInterface() ? 56 : 11);
        initEditBoxXPos = 14;
        initAllowedItemsLabelXPos = 155;
        initAllowedItemsLabelYPos = (menu.isFullInterface() ? 212 : 122);
        initAllowedRange = (menu.dualBlock ? 6401 : 3201);
        initExtraAreaYOffset = 20;
        initFoldable = true;

        editIcon = CFAGuiTextures.STURDY_EDIT;
        bgInvXOffset = 15;
        bgInvYOffset = (menu.isFullInterface() ? 67 : 22);
        bgAddTexXShift = false;
        bgAddTexYShift = true;
        secBgOffset = 109;
    }

    @Override
    public void renderForeground(@NotNull GuiGraphics ms, int mouseX, int mouseY, float partialTicks) {
        super.renderForeground(ms, mouseX, mouseY, partialTicks);

        int x = leftPos;
        int y = YShift + textureYShift;

        String itemCount = String.valueOf(menu.contentHolder.inventory.itemCount + (menu.dualBlock ? menu.contentHolder.getOtherCrate().inventory.itemCount : 0));
        ms.drawString(font, itemCount, x + 143 - font.width(itemCount), y + 126 + capacityLabelOffset, 0x4B3A22, false);

        for (int slot = 0; slot < (menu.isFullInterface() ? 100 : 50); slot++) {
            if (allowedCapacity.getState() - (menu.page == 1 && menu.isFold ? 50*64 : 0) > slot * 64)
                continue;
            int slotsPerRow = 10;
            int slotX = x + 13 + (slot % slotsPerRow) * 18;
            int slotY = y + 19 + (slot / slotsPerRow) * 18;
            CFAGuiTextures.STURDY_CRATE_LOCKED_SLOT.render(ms, slotX, slotY);
        }

/*========================================================================================================================================*/
/*  THIS PART OF THE CODE WAS GENERATED BY DEEPSEEK V4                                                                                    */
/*----------------------------------------------------------------------------------------------------------------------------------------*/
/**/    if (menu.dualBlock && foldButton != null && foldButton.isHovered()) {                                                           /**/
/**/        if (menu.isFold) {                                                                                                          /**/
/**/            ms.renderComponentTooltip(font,                                                                                         /**/
/**/                    List.of(Component.translatable("create_fantasizing.gui.crate.unfold")),                                    /**/
/**/                    mouseX, mouseY);                                                                                                /**/
/**/        } else {                                                                                                                    /**/
/**/            ms.renderComponentTooltip(font,                                                                                         /**/
/**/                    List.of(Component.translatable("create_fantasizing.gui.crate.fold")),                                      /**/
/**/                    mouseX, mouseY);                                                                                                /**/
/**/        }                                                                                                                           /**/
/*========================================================================================================================================*/
        }

        if (pageUpButton != null && pageUpButton.isHovered())
            ms.renderComponentTooltip(font, List.of(Component.translatable("create_fantasizing.gui.crate.next_page")), mouseX, mouseY);
        if (pageDownButton != null && pageDownButton.isHovered())
            ms.renderComponentTooltip(font, List.of(Component.translatable("create_fantasizing.gui.crate.prev_page")), mouseX, mouseY);

        GuiGameElement.of(renderedItem)
                .<GuiGameElement.GuiRenderBuilder>at(x + backgroundSec.getWidth(), y + background.getHeight() - 20 + itemYShift, -200)
                .scale(5)
                .render(ms);
    }
}
