package dev.hail.create_fantasizing.block.crate;

import dev.hail.create_fantasizing.block.CFAMenus;
import dev.hail.create_fantasizing.data.CFAAttachmentTypes;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.inventory.Slot;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.items.SlotItemHandler;
import org.jetbrains.annotations.NotNull;

/**
 * THIS CLASS WAS MODIFIED BY DEEPSEEK V4
 * SturdyCrateEntity -> AbstractCrateEntity
 */
public class SturdyCrateMenu extends AbstractCrateMenu {
    public SturdyCrateMenu(MenuType<?> type, int id, Inventory inv, RegistryFriendlyByteBuf extraData) {
        super(type, id, inv, extraData);
    }

    public SturdyCrateMenu(MenuType<?> type, int id, Inventory inv, AbstractCrateEntity be) {
        super(type, id, inv, be);
    }

    public static SturdyCrateMenu create(int id, Inventory inv, AbstractCrateEntity be) {
        return new SturdyCrateMenu(CFAMenus.STURDY_CRATE.get(), id, inv, be);
    }

    @Override
    protected void addSlots() {
        dualBlock = contentHolder.isDoubleCrate();
/*========================================================================================================================================*/
/*  THIS PART OF THE CODE WAS GENERATED BY DEEPSEEK V4                                                                                    */
/*----------------------------------------------------------------------------------------------------------------------------------------*/
/**/    if (player.level().isClientSide && hasNetworkFoldData) {                                                                        /**/
/**/        isFold = networkIsFold;                                                                                                     /**/
/**/        page = dualBlock ? networkPage : 0;                                                                                         /**/
/**/    } else {                                                                                                                        /**/
/**/        if (player.hasData(CFAAttachmentTypes.FOLD_INTERFACE))                                                                      /**/
/**/            isFold = player.getData(CFAAttachmentTypes.FOLD_INTERFACE);                                                             /**/
/**/        if (player.hasData(CFAAttachmentTypes.CRATE_PAGE))                                                                          /**/
/**/            page = player.getData(CFAAttachmentTypes.CRATE_PAGE);                                                                   /**/
/**/    }                                                                                                                               /**/
/**/    player.setData(CFAAttachmentTypes.FOLD_INTERFACE, isFold);                                                                      /**/
/**/    player.setData(CFAAttachmentTypes.CRATE_PAGE, page);                                                                            /**/
/*========================================================================================================================================*/
        int x = 14;
        int maxRow = isFullInterface() ? 10 : 5;
        for (int row = 0; row < maxRow; ++row) {
            for (int col = 0; col < 10; ++col) {
/*========================================================================================================================================*/
/*  THIS PART OF THE CODE WAS GENERATED BY DEEPSEEK V4                                                                                    */
/*----------------------------------------------------------------------------------------------------------------------------------------*/
/**/            if (isFullInterface()) {                                                                                                /**/
/**/                this.addSlot(                                                                                                       /**/
/**/                        new SlotItemHandler(col + row * 10 < 50 ? contentHolder.inventory : contentHolder.getOtherCrate().inventory,/**/
/**/                                col + row * 10 - (col + row * 10 < 50 ? 0 : 50), x + col * 18, row * 18 + 27));    /**/
/**/            } else if (dualBlock && isFold) {                                                                                       /**/
/**/                var inv = page == 0 ? contentHolder.inventory : contentHolder.getOtherCrate().inventory;                            /**/
/**/                this.addSlot(new SlotItemHandler(inv, col + row * 10, x + col * 18, row * 18 + 27));        /**/
/**/            } else {                                                                                                                /**/
/**/                this.addSlot(new SlotItemHandler(contentHolder.inventory, col + row * 10, x + col * 18, row * 18 + 27));/**/
/**/            }                                                                                                                       /**/
/*========================================================================================================================================*/
            }
        }
        // player Slots
        addPlayerSlots(38, isFullInterface() ? 246 : 156);
    }
}